In [4]:
import pandas as pd
import os
import datetime

In [5]:
def format_heure(chaine):
    if pd.isnull(chaine):
        return np.nan
    else:
        if chaine == 2400: chaine = 0
        chaine = "{0:04d}".format(int(chaine))
        heure = datetime.time(int(chaine[0:2]), int(chaine[2:4]))
        return heure
def create_flight_time(df, col):    
    liste = []
    for cols in df[col]:
        if pd.isnull(cols):
            liste.append(np.nan)
        elif float(cols) == 2400:
            cols = datetime.time(0,0)
            liste.append(cols)
        else:
            cols = format_heure(cols)
            liste.append(cols)
    return pd.Series(liste)

def concatenate():

    # load csv file containing the airport information
    airport_df = pd.read_csv("./airports.csv")

    #load csv file containing the flight delay information. this will be the main dataframe
    flights_df =  pd.read_csv('/home/chun/Desktop/gpr_testing/flight/flights.csv')
    main_df = flights_df
    # combine these, so that the main dataframe has latitude longitude information
    airport_df = airport_df.set_index("IATA_CODE")
    for loc in ['ORIGIN','DESTINATION']:
        for dir in ['LATITUDE','LONGITUDE']:
            main_df[loc+'_'+dir] =(airport_df[dir][flights_df[loc+"_AIRPORT"][:]]).reset_index()[[dir]]
#     main_df.to_csv("{}.txt".format('processed'))

    main_df['SCHEDULED_DEPARTURE'] = create_flight_time(main_df, 'SCHEDULED_DEPARTURE')
    main_df['SCHEDULED_HOUR']=pd.to_datetime(main_df['SCHEDULED_DEPARTURE'], format='%H:%M:%S').dt.hour
    airline_dummy = pd.get_dummies(main_df['AIRLINE'])
    main_df = main_df.merge(airline_dummy, left_index=True, right_index=True)
#     variables_to_remove = ['YEAR', 'DAY', 'AIRLINE', 'FLIGHT_NUMBER',
#        'TAIL_NUMBER', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT',
#        'SCHEDULED_DEPARTURE', 'DEPARTURE_TIME', 'TAXI_OUT',
#        'WHEELS_OFF', 'SCHEDULED_TIME', 'ELAPSED_TIME', 'AIR_TIME', 
#        'WHEELS_ON', 'TAXI_IN', 'SCHEDULED_ARRIVAL', 'ARRIVAL_TIME',
#        'DIVERTED', 'CANCELLED', 'CANCELLATION_REASON',
#        'AIR_SYSTEM_DELAY', 'SECURITY_DELAY', 'AIRLINE_DELAY',
#        'LATE_AIRCRAFT_DELAY', 'WEATHER_DELAY']
    variables_to_remove = ['YEAR', 'DAY', 'AIRLINE', 'FLIGHT_NUMBER',
       'TAIL_NUMBER', 
       'SCHEDULED_DEPARTURE', 'DEPARTURE_TIME', 'TAXI_OUT',
       'WHEELS_OFF', 'SCHEDULED_TIME', 'ELAPSED_TIME', 'AIR_TIME', 
       'WHEELS_ON', 'TAXI_IN', 'SCHEDULED_ARRIVAL', 'ARRIVAL_TIME',
       'DIVERTED', 'CANCELLED', 'CANCELLATION_REASON',
       'AIR_SYSTEM_DELAY', 'SECURITY_DELAY', 'AIRLINE_DELAY',
       'LATE_AIRCRAFT_DELAY', 'WEATHER_DELAY']
    main_df.drop(variables_to_remove, axis = 1, inplace = True)
    main_df.dropna(inplace = True)

    return main_df

In [6]:
if __name__ == "__main__":
    main_df = concatenate()
    main_df.to_csv("{}.txt".format('processed_airport'))

/home/chun/py/py3env/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2903: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

In [11]:
airport_df = pd.read_csv("./airports.csv")

#load csv file containing the flight delay information. this will be the main dataframe
flights_df =  pd.read_csv('/home/chun/Desktop/gpr_testing/flight/flights.csv')
main_df = flights_df

SyntaxError: invalid syntax (<ipython-input-11-6f4609e4395e>, line 9)

In [12]:
main_df.iloc[100:110]

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
100,2015,1,1,4,EV,5498,N132EV,ORD,DTW,535,...,757.0,-3.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
101,2015,1,1,4,OO,6512,N925SW,FAT,LAX,535,...,650.0,0.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
102,2015,1,1,4,UA,1577,N69813,SMF,DEN,538,...,1018.0,78.0,0,0,NaN,22.0,0.0,56.0,0.0,0.0
103,2015,1,1,4,OO,4986,N719SK,AUS,LAX,538,...,654.0,-16.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
104,2015,1,1,4,B6,727,N292JB,BOS,BWI,540,...,700.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
105,2015,1,1,4,B6,1012,N375JB,ORD,BOS,540,...,823.0,-33.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
106,2015,1,1,4,DL,824,N3736C,PHX,DTW,540,...,1331.0,128.0,0,0,NaN,0.0,0.0,0.0,0.0,128.0
107,2015,1,1,4,DL,941,N910DN,MCI,ATL,540,...,827.0,-15.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
108,2015,1,1,4,DL,2079,N389DA,BOS,DTW,540,...,742.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
109,2015,1,1,4,EV,3268,N14998,ATL,IAD,540,...,739.0,14.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN